### ISSUE TITLE
Expose angular module name

### ISSUE THREAD

**Issue by egaga** [EvidentSolutions/apina#20]
in the generated api file:

var apinaModule = angular.module('apina.api', []);

The module or its name should be exposed so that one can depend on it with static verification.
e.g. import api = require('api-definitions/api');
Should hold: 'apina.api' === api.Support.Angular.apinaModule

Similarly for 'apina.endpoints'

**Comment by komu** [comment]
I'm not too keen on this: this seems to enlarge the API surface (and therefore the amount of documentation one needs to read) for little or no benefit.

If the module would be something that you'd use again and again in your program, I'd agree that a constant would be necessary. But in reality, you only have to specify it once and I find it hard to believe that  a constant would catch any actual bugs occurring in the wild. I've never seen a project that would provide a constant for its module names and I've never had bugs because of that. And even if you would manage to mistype the module name, it wouldn't cause lurking bugs but the app would fail to start right away.
