### ISSUE TITLE
Generation should fail on nonsensical endpoint definitions

### ISSUE THREAD

**Issue by egaga** [EvidentSolutions/apina#45]
Consider the following endpoint definition:

```
@GetMapping("/foo/{blaa}")
fun findMe(@PathVariable wobble: Int) = "wobble is not blaa"
```

Apina translates this into typescript endpoint service method which fails at runtime.

**Comment by komu** [comment]
I'd rather not take that route. Although most of the time path-variables are statically resolved to request-parameters, you can access them in another way as well. And sometime one uses dummy path-variables simply for regex-matching purposes:

```java
@GetMapping("/foo/{dummy:[0-9]+}/{interestingValue}")
```

But even if this is legal, what's the point if generated client code can't use these?

First of all it's possible that a controller contains some methods that are not really meant to be used by Apina. Perhaps there are some actions for downloading resources etc. It would be rude of Apina to fail compilation just because there are some methods it doesn't like.

Second of all, it is possible for Apina to use this. Your original code would translate to this:

```typescript
findMe(wobble: number): Observable<string> {
    return this.context.request({
        'uriTemplate': '/foo/{blaa}',
        'method': 'GET',
        'pathVariables': {
            'wobble': this.context.serialize(wobble, 'number')
        },
    });
}
```

Sure, `DefaultApinaEndpointContext` will fail with that, but a custom implementation may do anything it wishes. As a realistic example, consider an API that passes some session tokens in URLs (not that I'm really advocating for this):

```kotlin
@GetMapping("/{sessionToken}/frobnicate/{id}")
fun frobnicate(@PathVariable id: Int) = ...
```

It might be nice to handle session-tokens in generic interceptors both on client and server side and Apina let's you do just that. You can create a custom `ApinaEndpointContext` that substitutes `sessionToken`-path variables and a Spring interceptor that knows how to read them.

Now I understand that these are quite rare cases. Could Apina give a warning? I'm not completely opposed to that, but I'd rather keep Apina focused on one thing instead of turning it into an API-lint. I that warning about things like this is IDE's job and IDEA does exactly that:

![screen shot 2018-08-28 at 10 09 23](https://user-images.githubusercontent.com/3473/44706515-79d58a00-aaaa-11e8-80ab-abd0747cde93.png)

So the real problem is that IDEA's Spring inspections don't yet support Kotlin as well as Java. I think this will improve over time.
