### ISSUE TITLE
Support creating dynamic URLs in typescript based on endpoints

### ISSUE THREAD

**Issue by hakuzumon** [EvidentSolutions/apina#48]
Use case: I need to generate an excel file download URL, that has somewhat complex query parameters (a list of enums).

It would be really nice if I could use Apina's mechanisms to create this URL. Like such:

```java
@RestController
class DownloadController {

  @ApinaUrlGenerator
  @RequestMapping(value = "/download-the-thing", method = GET, produces = "application/the-thing")
  Object downloadTheThing(@RequestParam List<MyEnum> myEnums) { ... }
}
```

And then I could call it from typescript, like so:

```java
const downloadUrl: string = downloadEndpoint.downloadTheThing([enumValue1, enumValue2]);
```

Is this reasonable? If it is, what should be the name for the controller method annotation?

**Comment by javier-vilares** [comment]
@komu , what about adding a flag in the settings and allow to generate the url for every endpoint?

Benefits:
- No need to add custom annotations

Drawbacks:
- Some unused code generated, it may be more work to the IDE to index (in the prod build tree shaking would take care of it)

I gave it a try here:
https://github.com/javier-vilares/apina/commit/e9028b4c2dafb9ce274c6bf19ec33136bb87a7ed

Maybe making "buildUrl" public it´s not a good idea, but I didn´t want to change too many code. The impl would also need:

- To include query params in the method.
- Tests
- Better code quality and naming

**Comment by komu** [comment]
Hi, @javier-vilares, I somehow missed your comment earlier.

The code looks quite ok, but there's at least one problem: if the controller method includes `@RequestBody`-parameters, they should probably be removed from the generated URL-methods, since they make no sense in URL-generation.

Unless using some really aggressive shakers, tree-shaking will not probably remove methods from the endpoint-classes because it's impossible to determine statically if a member of JavaScript object is accessed or not. Normally tree-shaking works on module exports.

Anyway, in a normal project there are probably only a few methods that one would like to generate URLs for. So perhaps we could just match against them using a regex, similarly how you can use regex to select endpoints to process. So by default the matching regex would be just an empty string that would match nothing, but you could say `foo\.bar\.MyController\.myMethod` or ``foo\.bar\.MyController\..+`, or even `.+` if you want URL-methods for everything. It would be somewhat tedious if you'd like to pick 10 methods, but it could still be done.

**Comment by javier-vilares** [comment]
Hi @Komu, I think you are right, the regex solution would be the best given the constraints, having that flexibility would be really nice!

**Comment by komu** [comment]
@javier-vilares, @hakuzumon 

I just pushed the branch https://github.com/EvidentSolutions/apina/compare/master...feat/endpoint-urls which implements this. Care to look at the design and documentation for this? I'll still add some tests before merging, but otherwise I think it could work like that.

**Comment by javier-vilares** [comment]
It seems perfect :D

I only found two typos in _05-custom-request.adoc
```
 line 85: @RequestParan 
 line 113: ot
```

I also tested it manually in a project and worked as expected.

**Comment by komu** [comment]
Thanks a lot, fixed the typos.

**Comment by komu** [comment]
I released `0.13.5` which includes this.

**Comment by hakuzumon** [comment]
Awesome, thanks!

**Comment by komu** [comment]
Now afterwards I think that I may have made a mistake in that Apina generates both the original method and the URL accessor. Perhaps (by default) Apina should omit the original method if URL accessor is generated. Perhaps I have something like the following:

```kotlin
@GetMapping("/download/{name}.pdf")
fun downloadPdf(@PathVariable name: String): PdfData {
    ...
}
```

Now it's obvious that I don't want Apina to read `PdfData` and create classes from it as if it would ever be converted to JSON. But it won't be, since it will be picked up by some custom `HandlerMethodReturnValueHandler` there's no reason to generate a method for calling this. I suspect that this is the case practically always.

@javier-vilares, @hakuzumon, how do you feel? Do you have examples of methods where you'd want both behaviors? I think I'm going to make a technically backwards incompatible change here because it probably won't affect anyone.

**Comment by hakuzumon** [comment]
When I saw earlier that it now generates both, my initial thought was "what use is there for the original method?" But then I saw you mention "exotic use cases" and thought that maybe there are such. But I can't think of any right now.

**Comment by javier-vilares** [comment]
I only use it for downloading pictures/files/videos, I don't have any other use case.

However, generating both methods allows me to just put a ".+/" regular expression in the projects where I prefer a little bigger build size than having to mantain a list of paths that may break when changing the method name or the package during a refactor.

I could change the regular expression to generate the url methods only for methods that contain the "download" keywoad, and enforce this convention in the team. I could totally live with that, so probably if you change this behaviour you would force lazy developers like me to follow better practices, which is probaby a good thing :smile:
