### ISSUE TITLE
Externalized serialization configuration

### ISSUE THREAD

**Issue by jvmlet** [EvidentSolutions/apina#60]
Would you please externally expose  the configuration for ignored fields when generating `ts` classes ?
Currently, you are skipping fields/getters annotated with `@JsonIgnore`, which is not always sufficient, think about `@Transient` or any custom or third-party  annotation.
The configuration could be annotation class name  to check on field/getter to decide whether  to include or exclude the field and looks like this in gradle:

````groovy
{
fieldsToIgnore {
 annotatedWith : [ 'java.beans.Transient' ]
}
}
````

**Comment by komu** [comment]
Thanks for your input.

I agree, that some solution should be provided, but perhaps we could even avoid extra configuration for this? Let me explain myself a bit (and think this one aloud).

Certainly it would be easiest to just add some list of annotations that would then function like `@JsonIgnore`. Problem is that, different ignore mechanisms have slightly mechanisms with respect to inheritance, mutual overrides etc. Of course it would be possible to just decide that the straightforward implementation would be good enough and the corner cases don't appear practice. Furthermore, all exposed API elements (such as configuration) will cause friction on future changes, because they limit the options that are available without breaking compatibility. 

On the other hand there's the issue of documentation. If Apina more manual tuning, then it requires more documentation. I have nothing against writing it, per se, but it makes the documentation longer and less focused. I've tried really hard to make it as short as possible in the hope that people will actually bother to read it. Part of this is of course just an issue of how to document things, but part of it is also deciding which features to include and which to exclude. Generally I've tried to make Apina smarter and leverage Jackson's configuration.

Which brings me to my last point: even without any configuration, Apina should have the same defaults as Jackson. So as it seems that Jackson supports `java.beans.Transient` (FasterXML/jackson-databind#857), so should Apina. It seems that Jackson just hard-codes this support and I feel like Apina should take the same route.

Now all of these don't mean that I won't implement this option, but these are my concerns.

Anyway, I feel like starting by just hard-coding support for `java.beans.Transient` should make a good start. If necessary, than can later be turned into configurable mechanism without breaking anyone, whereas going to other direction is more painful.

Do you have problems with any other annotations? If there are several commonly used annotations that Jackson supports, I can implement support for all of them. Or do you have a concrete example where supporting arbitrary annotations would be necessary?

Thanks again, I'll implement at least the `java.beans.Transient`-support soon.

**Comment by jvmlet** [comment]
Thanks for your replay, @komu . To tell the truth ,`java.beans.Transient`  was obvious example, but we are using  `org.springframework.data.annotation.Transient` annotation on our generated pojos fields.
While I think it would be easy for us to add `java.beans.Transient` annotation  together with `org.springframework.data.annotation.Transient`,   people who don't have  control on classes they are transmitting would have problems cutting off things they don't want.

I understand your concern about being backward compatible when you expose configuration, on the other hand I don't mind read upgrade guide (which has too be written too  ;-)   )

IMHO, the most powerful and least dangerous solution would be to expose callback passing class name and getting back fields to include, your default implementation will strip down fields annotated with  `@JsonIgnore` and `@Transient`

Thanks for Apina, it saves us a LOT  of efforts. Keep up.

**Comment by komu** [comment]
I guess Spring Data automatically adds some Jackson-configuration so that `org.springframework.data.annotation.Transient` is automatically ignored?

If there's a small number of well-known annotations, I guess it would be nice if Apina would automatically just work for them. It'd be really weird if someone would have annotated a property with `org.springframework.data.annotation.Transient`, but would want Apina to include it.

>IMHO, the most powerful and least dangerous solution would be to expose callback passing class name and getting back fields to include

That's certainly the most powerful, but I think it's also quite dangerous. It would certainly freeze some aspects of the implementation strategy pretty heavily in place and while I can't see right now why it would be a problem, I would hesitate adding such a sharp tool without very good reasons. In the past, I've done quite a lot of internal refactoring (such as making evaluation lazier) to facilitate performance improvements. APIs like that are hard to deal with in such situations.

So as a strawman, let's suppose that we'd pass in the class and get back fields to include. What does "fields" mean here? Is is just field names? If so, how does Apina resolve their types? If the callback says that a `foo` is to be included, but Apina has no evidence of `foo` being present in the class, how should it proceed? The extreme option would to be basically let the user perform all of the work in `JacksonTypeTranslator.translateType`, but that would have negative consequences:

1. Even larger part of Apina's internal model would become public API surface
2. User would be responsible for implementing too much of the complexity
3. Once you'd start using the API, you'd lose all the future improvements to `translateType`

Of course there might be a sweet spot somewhere in the middle, but it's not completely obvious what it is. There are trade-offs everywhere.

Generally I try to follow the [rule of least power](https://www.w3.org/2001/tag/doc/leastPower.html) as far as possible because once you expose too much power, your tool can no longer be smart: it can just blindly execute the commands instead of analyzing the rules. (As a digression, I'm waiting for the day when we get usable programming languages where even features like general recursion are tucked away into a monad, effect system, unsafe-mechanism or something like that. Cool program transformations and language features come to those who are willing to give up some power in normal code. I don't need my language to be Turing complete for 99% of the time.)

Sorry, back to business.

A less intrusive API would be a predicate-callback that would receive class name and a property and would return a boolean indicating whether it would be included or not. Pretty safe, not really affecting evaluation order on Apina's side and generally keeping the boundaries between the different parts of algorithm clear. However, if it's not really needed for anything, I still would not want to add it just because it's easy and possible.

So what I'll do now is that I'll add a manual support for `org.springframework.data.annotation.Transient` as well because it solves your problems and will keep all options open for the future. If similar use cases pop up in the future, I'll reconsider if there's a need for more general solution.

**Comment by jvmlet** [comment]
Thanks @komu , it does make sense.

**Comment by jvmlet** [comment]
BTW, if we are already talking about transients, what about `transient` keyword  in field definition?

**Comment by komu** [comment]
Right, I aligned Apina's behavior with Jackson with regards to transient fields.

By the way, from the very beginning of Apina I have considered exposing an even more powerful API that might also solve this problem:

After Apina has built the whole model by scanning the classes, but before it starts spitting out TypeScript, it could pass the model to a callback that could make arbitrary modifications to it. The API would come with no compatibility guarantees at all, but of course the model between frontend and backend is relatively stable, so it breakage would probably be minimal. And of course the API itself would be a escape hatch when nothing else will do.

Then again, I'm afraid that if an API like that is available, people will just use that instead of complaining to me and I'll never learn of the actual needs of the users. Then they'll going on using a lower-level solution when a nice real solution could be easily implemented in Apina.

I just released `0.13.2` with these changes. I'll close this issue for know, but I'll keep the ideas in mind and might generalize these mechanisms later, if a need arises.

Thanks for the issue and your comments!

**Comment by jvmlet** [comment]
Thanks a lot

**Comment by jvmlet** [comment]
I think you had typo in version - you released  `1.3.2` instead  `0.13.2`...

**Comment by komu** [comment]
Right! 😆 Sorry..

**Comment by jvmlet** [comment]
Also, the annotation on field doesn't  have any effect, only on getter method :-(

**Comment by komu** [comment]
The annotation should work on a field, but I guess you have a private field with a public getter? In that case, the annotation is indeed not considered. Does Jackson really honor the annotation on a private field even though serialization is done using the getter?

As of this moment, Apina considers private fields completely as implementation details.

**Comment by komu** [comment]
I published the same bits as `0.13.2` for now as well. But since Gradle plugin portal wants to show the highest version as default, I think I'll have to do a version number jump.

Funny, just yesterday I was considering that I should probably do `1.x` release someday, but this certainly speeds it up a bit unless I can unlist the published version. 😄

**Comment by jvmlet** [comment]
yes, I have private field with annotation and public getter, I'm almost sure Jackson deals with this properly.

**Comment by komu** [comment]
Ok, I managed to delete `1.3.2` for now, so you'll need to use`0.13.2`. So if I'll get to releasing `1.x` I will start it normally with. `1.0`. Sorry for the hassle.

As for the mapping logic, I guess I can modify the code to the corresponding field if it's present. It feels a bit dirty, but if it's how Spring Data configures Jackson, so be it.

**Comment by jvmlet** [comment]
It's not related to Spring Data, actually Spring Data for Elasticsearch dropped json mapping  in favor of  native ES document mapping. 
This  is about Jackson feature that allows to have `@JsonIgnore` on private field. I think it would be logical to support same behavior  (different annotations types though ) as Jackson does.

**Comment by komu** [comment]
Well now you can take `0.13.3` out for a spin. It first tries to look for annotations in public methods, then fallbacks to field if there is a correspondingly named field which has annotations.

**Comment by jvmlet** [comment]
Nope 😢 ,  I have the field defined like this :

```java
  @org.springframework.data.annotation.Transient
  private Builder messageBuilder;
```

without getter method, and `0.13.3` still tries to include  `messageBuilder` into `ts` class

**Comment by komu** [comment]
Hmm, can you provide a minimal, yet complete example of a class that produces invalid results. That seems weird because I have this test class:

https://github.com/EvidentSolutions/apina/blob/9e818471eba017b15355e900be0c7431425bfb39/apina-core/src/test/java/fi/evident/apina/spring/testclasses/ClassWithSpringDataTransient.java#L1-L23

along with this test case which checks that only `foo` is included and `bar` and `baz` are ignored:

https://github.com/EvidentSolutions/apina/blob/9e818471eba017b15355e900be0c7431425bfb39/apina-core/src/test/kotlin/fi/evident/apina/spring/JacksonTypeTranslatorTest.kt#L154-L159

**Comment by jvmlet** [comment]
I think I know what's happening. In addition to the field annotated with `@Transient`, I also have getter for this field (not annotated) which does not follow bean convention, like `getMessage` that returns `originalMessage` field. So `message` and `originalMessage`are treated as  2 fields, one included, another one excluded. Will be able to confirm this tomorrow. Thanks and sorry for hassling

**Comment by jvmlet** [comment]
Indeed, that is what happened. Following bean convention is always a good practice 😄 
Thanks a lot, @komu
