### ISSUE TITLE
How to configure baseURL from Springboot Gradle to reflect in .ts file at react frontend

### ISSUE THREAD

**Issue by Drashti-Patel** [EvidentSolutions/apina#73]
I want to pass baseURL, when I sync apina with front end from my Springboot backend. Is there any way I can run any Gradle task for it?

export class ApinaConfig {
  /** Prefix added for all API calls */
  baseUrl: string = ''

  private serializers: SerializerMap = {
    any: identitySerializer,
    string: identitySerializer,
    number: identitySerializer,
    boolean: identitySerializer,
  }

**Comment by komu** [comment]
You can't configure it on build time, but you can simply set the preferred `baseUrl` in runtime.

So first we'll need a  function to construct the preferred configuration. In my project, I simply get the value from [Angular's environment file](https://angular.io/guide/build#configuring-application-environments) and pass it in:

```typescript
export function createApinaConfig(): ApinaConfig {
    const config = new ApinaConfig();
    config.baseUrl = environment.baseUrl;
    return config;
}
```

Of course you could just hard-code the value, or write some code to dynamically compute it from `window.location` or some other value.

Once we have the function create our configuration, we have to tell Angular that we want to use it to construct our configuration instead of using the default configuration:

```typescript
@NgModule({
    ...
    providers: [
        {provide: ApinaConfig, useFactory: createApinaConfig},
    ]
})
export class AppModule {
}
```

(Assuming you are using the Angular output mode. If not, then you are already creating the configuration manually and can just parameterize if normally by setting `baseUrl` like above.)

Hope this helps.
